//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekendTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackendBemaxEntities : DbContext
    {
        public BackendBemaxEntities()
            : base("name=BackendBemaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SliderProject> SliderProjects { get; set; }
        public virtual DbSet<Testiminiol> Testiminiols { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ImgContent> ImgContents { get; set; }
        public virtual DbSet<Choose> Chooses { get; set; }
        public virtual DbSet<Working> Workings { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<BlogPost> BlogPosts { get; set; }
    }
}
